name: Build Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build:
    needs: [init]
    uses: ./.github/workflows/build-workflow.yml
    with:
      skip-tests: true