name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Grant execution permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
