name: Main Workflow

on:
  push:
    branches:
      - main
      - 9-fix-github-actions-main-workflow-bug

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build:
    needs: [init]
    uses: ./.github/workflows/build-workflow.yml
    with:
      skip-tests: false

  test:
    needs: [build]
    uses: ./.github/workflows/test-workflow.yml
    with:
      abort-on-failure: true