name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Build
        uses: ./.github/workflows/build.yml

      - name: Test
        uses: ./.github/workflows/test.yml