name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant execution permission for gradlew
        run: chmod +x gradlew

      - name: Test
        continue-on-error: true
        run: ./gradlew test
