name: Test Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  test:
    needs: [init]
    uses: ./.github/workflows/test-workflow.yml
    with:
      abort-on-failure: false